package Fact;


/**
* Fact/FactorialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fact.idl
* Monday, April 27, 2015 2:24:56 PM PDT
*/

public interface FactorialOperations 
{
  int fact (int number1);
  void shutdown ();
} // interface FactorialOperations
