package Fact;

/**
* Fact/FactorialHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fact.idl
* Monday, April 27, 2015 2:24:56 PM PDT
*/

public final class FactorialHolder implements org.omg.CORBA.portable.Streamable
{
  public Fact.Factorial value = null;

  public FactorialHolder ()
  {
  }

  public FactorialHolder (Fact.Factorial initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Fact.FactorialHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Fact.FactorialHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Fact.FactorialHelper.type ();
  }

}
