package Fact;


/**
* Fact/FactorialHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fact.idl
* Monday, April 27, 2015 2:24:56 PM PDT
*/

abstract public class FactorialHelper
{
  private static String  _id = "IDL:Fact/Factorial:1.0";

  public static void insert (org.omg.CORBA.Any a, Fact.Factorial that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Fact.Factorial extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Fact.FactorialHelper.id (), "Factorial");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Fact.Factorial read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FactorialStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Fact.Factorial value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Fact.Factorial narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fact.Factorial)
      return (Fact.Factorial)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fact._FactorialStub stub = new Fact._FactorialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Fact.Factorial unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fact.Factorial)
      return (Fact.Factorial)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fact._FactorialStub stub = new Fact._FactorialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
