
/**
* Add.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Tuesday, April 21, 2015 6:37:33 PM PDT
*/

public interface Add extends AddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Add
