
/**
* AddHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Tuesday, April 21, 2015 6:37:33 PM PDT
*/

public final class AddHolder implements org.omg.CORBA.portable.Streamable
{
  public Add value = null;

  public AddHolder ()
  {
  }

  public AddHolder (Add initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddHelper.type ();
  }

}
