
/**
* AddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Tuesday, April 21, 2015 6:37:33 PM PDT
*/

public interface AddOperations 
{
  int math_op (int param1, int param2, int param3);
} // interface AddOperations
