//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMessageWebApplication.TextMessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextMessageService.TextMessageWebServiceSoap")]
    public interface TextMessageWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TextMessageWebApplication.TextMessageService.HelloWorldResponse HelloWorld(TextMessageWebApplication.TextMessageService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.HelloWorldResponse> HelloWorldAsync(TextMessageWebApplication.TextMessageService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name toNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTextMessage", ReplyAction="*")]
        TextMessageWebApplication.TextMessageService.SendTextMessageResponse SendTextMessage(TextMessageWebApplication.TextMessageService.SendTextMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTextMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.SendTextMessageResponse> SendTextMessageAsync(TextMessageWebApplication.TextMessageService.SendTextMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TextMessageWebApplication.TextMessageService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TextMessageWebApplication.TextMessageService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TextMessageWebApplication.TextMessageService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TextMessageWebApplication.TextMessageService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextMessage", Namespace="http://tempuri.org/", Order=0)]
        public TextMessageWebApplication.TextMessageService.SendTextMessageRequestBody Body;
        
        public SendTextMessageRequest() {
        }
        
        public SendTextMessageRequest(TextMessageWebApplication.TextMessageService.SendTextMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendTextMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string carrier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string attachment;
        
        public SendTextMessageRequestBody() {
        }
        
        public SendTextMessageRequestBody(string toNumber, string carrier, string subject, string body, string attachment) {
            this.toNumber = toNumber;
            this.carrier = carrier;
            this.subject = subject;
            this.body = body;
            this.attachment = attachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TextMessageWebApplication.TextMessageService.SendTextMessageResponseBody Body;
        
        public SendTextMessageResponse() {
        }
        
        public SendTextMessageResponse(TextMessageWebApplication.TextMessageService.SendTextMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendTextMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTextMessageResult;
        
        public SendTextMessageResponseBody() {
        }
        
        public SendTextMessageResponseBody(string SendTextMessageResult) {
            this.SendTextMessageResult = SendTextMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextMessageWebServiceSoapChannel : TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextMessageWebServiceSoapClient : System.ServiceModel.ClientBase<TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap>, TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap {
        
        public TextMessageWebServiceSoapClient() {
        }
        
        public TextMessageWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextMessageWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextMessageWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextMessageWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMessageWebApplication.TextMessageService.HelloWorldResponse TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap.HelloWorld(TextMessageWebApplication.TextMessageService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TextMessageWebApplication.TextMessageService.HelloWorldRequest inValue = new TextMessageWebApplication.TextMessageService.HelloWorldRequest();
            inValue.Body = new TextMessageWebApplication.TextMessageService.HelloWorldRequestBody();
            TextMessageWebApplication.TextMessageService.HelloWorldResponse retVal = ((TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.HelloWorldResponse> TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap.HelloWorldAsync(TextMessageWebApplication.TextMessageService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.HelloWorldResponse> HelloWorldAsync() {
            TextMessageWebApplication.TextMessageService.HelloWorldRequest inValue = new TextMessageWebApplication.TextMessageService.HelloWorldRequest();
            inValue.Body = new TextMessageWebApplication.TextMessageService.HelloWorldRequestBody();
            return ((TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextMessageWebApplication.TextMessageService.SendTextMessageResponse TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap.SendTextMessage(TextMessageWebApplication.TextMessageService.SendTextMessageRequest request) {
            return base.Channel.SendTextMessage(request);
        }
        
        public string SendTextMessage(string toNumber, string carrier, string subject, string body, string attachment) {
            TextMessageWebApplication.TextMessageService.SendTextMessageRequest inValue = new TextMessageWebApplication.TextMessageService.SendTextMessageRequest();
            inValue.Body = new TextMessageWebApplication.TextMessageService.SendTextMessageRequestBody();
            inValue.Body.toNumber = toNumber;
            inValue.Body.carrier = carrier;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.attachment = attachment;
            TextMessageWebApplication.TextMessageService.SendTextMessageResponse retVal = ((TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap)(this)).SendTextMessage(inValue);
            return retVal.Body.SendTextMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.SendTextMessageResponse> TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap.SendTextMessageAsync(TextMessageWebApplication.TextMessageService.SendTextMessageRequest request) {
            return base.Channel.SendTextMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextMessageWebApplication.TextMessageService.SendTextMessageResponse> SendTextMessageAsync(string toNumber, string carrier, string subject, string body, string attachment) {
            TextMessageWebApplication.TextMessageService.SendTextMessageRequest inValue = new TextMessageWebApplication.TextMessageService.SendTextMessageRequest();
            inValue.Body = new TextMessageWebApplication.TextMessageService.SendTextMessageRequestBody();
            inValue.Body.toNumber = toNumber;
            inValue.Body.carrier = carrier;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.attachment = attachment;
            return ((TextMessageWebApplication.TextMessageService.TextMessageWebServiceSoap)(this)).SendTextMessageAsync(inValue);
        }
    }
}
